# Generated by Django 5.1.5 on 2025-01-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.BooleanField(default=True, verbose_name='Type (checked - income, not checked - outcome)'),
        ),
    ]
