# Generated by Django 5.1.5 on 2025-02-02 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financemanager", "0002_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
