# Generated by Django 5.1.5 on 2025-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financemanager", "0003_alter_transaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("INCOME", "Income"), ("OUTCOME", "Outcome")],
                default="OUTCOME",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("INCOME", "Income"), ("OUTCOME", "Outcome")],
                default="OUTCOME",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
