# Generated by Django 5.1.5 on 2025-02-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
